POST http://localhost:3003/api/login 
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "salainen"
   
   
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Didi",
    "name": "Didi",
    "password": "Zhasur!72"
   
}




###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzQwNDYwNGMzZmRiMjQ5YTEyMjVhZDciLCJpYXQiOjE3MzQ5NzIwMDEsImV4cCI6MTczNTAwODAwMX0.ENCNbneus9x6ltWG9bd4KPm1zECLozsXTp9jAonZ1BI


{
    "title": "Mahtava testi",
    "author": "Matti Luukkainen",
    "url": "www.testi.fi",
    "likes": 1111111
}


### 
GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzQwNDYwNGMzZmRiMjQ5YTEyMjVhZDciLCJpYXQiOjE3MzQyNTk4NTUsImV4cCI6MTczNDI2MzQ1NX0.HvCwBrMkelZQUCs9safOxqMPB6hK8Y6tzOgcBN5dXgI


