POST http://localhost:3003/api/login 
Content-Type: application/json

{
    "username": "sabisabi",
    "password": "salomat"
   
   
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "sabisabi",
    "name": "fiksu",
    "password": "salomat"
   
}




###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhYmlzYWJpIiwiaWQiOiI2NzY5ZDg0MTYwMjAyZTQxZGNjN2FmMzYiLCJpYXQiOjE3MzUxMjQ0MjAsImV4cCI6MTczNTEyODAyMH0.5EChmAD8ybB9iNn2JQTnbr_MW814o_39XU2x9PxKv_E


{
    "title": "Taas sabin testi",
    "author": "älykas",
    "url": "www.testi.fi",
    "likes": 222222222
}


# ### 
# GET http://localhost:3003/api/blogs
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NzQwNDYwNGMzZmRiMjQ5YTEyMjVhZDciLCJpYXQiOjE3MzQyNTk4NTUsImV4cCI6MTczNDI2MzQ1NX0.HvCwBrMkelZQUCs9safOxqMPB6hK8Y6tzOgcBN5dXgI


